server:
  port:
    80

spring:
#数据库连接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myvhr?serverTimezone=UTC&userSSL=false
    username: root
    password: root
#连接池配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    minIdle: 5
    maxActive: 20
    maxWait: 3000

  thymeleaf:
    cache: false
    encoding: UTF-8
#redis配置
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 10000

#mapper映射
mabatis:
  type-aliases-package: com.praysam.demo1.pojo
  mapper-locations: classpath:mapper/*.xml

#日志
logging:
  file:
    path: ./log
  level:
    net.praysam.demo1: DEBUG
